### ISSUE TITLE
How can i use this codelab online without the localhost?

### ISSUE THREAD

**Issue by OlgunF** [saurabharch/push-rest#5]
Hi Mr. Kashyap,

thanks for this awesome codelab. 

I learned a lot by working with it, but my question is, how can i use this online without the localhost? If i set this application online with a costum-domain, the settings doesn't work and it is impossible to save the subscriptions or to send messages to my application with postman. 

I get the following error: 

<img width="453" alt="problem1" src="https://user-images.githubusercontent.com/57448919/69487672-3fe66580-0e5e-11ea-8217-e1e44a78c01e.PNG">

Please can you tell me, what i have to do or what i have to change? 
I think, the problem is with my app.js file. 

<img width="574" alt="problem1 1" src="https://user-images.githubusercontent.com/57448919/69487710-c733d900-0e5e-11ea-80aa-5bd5e7989163.PNG">

Should i also have to change the post route of subscribe in push.js and subscribe.js? If yes, how is this possible?

<img width="607" alt="problem1 2" src="https://user-images.githubusercontent.com/57448919/69487761-be8fd280-0e5f-11ea-9521-e8c2657af4af.PNG">
<img width="630" alt="problem1 3" src="https://user-images.githubusercontent.com/57448919/69487762-c18ac300-0e5f-11ea-9521-db6ba7bdd8ab.PNG">

I hope, you have time and can help me to solve this issue. Thank you in advance!

**Comment by saurabharch** [comment]
Update your server side and client side public folder service worker public key which is generated by VAPID, it must be unique.
