### ISSUE TITLE
Does not work with Edge

### ISSUE THREAD

**Issue by nitrovent** [saurabharch/push-rest#6]
I have successfully tested this demo app in Chrome and in Firefox, however I could not get it to work with Edge since it throws an AbortError when trying to create the subscription.

I get the following output from the app:
```
Service Worker and Push is supported
service worker registered
Failed to subscribe user:  AbortError
```

The error occurs in line 39 of app.js

**Comment by saurabharch** [comment]
Cors isssue is fixed now
